CREATE TABLE IF NOT EXISTS user_activity (
  userId CHAR(36) NOT NULL PRIMARY KEY,
  lastActive TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
)