CREATE TABLE IF NOT EXISTS blog_tags (
  blogId CHAR(36) NOT NULL,
  tagId CHAR(36) NOT NULL,
  PRIMARY KEY (blogId, tagId),
  FOREIGN KEY (blogId) REFERENCES blogs(id) ON DELETE CASCADE,
  FOREIGN KEY (tagId) REFERENCES tags(id) ON DELETE CASCADE
)