CREATE TABLE IF NOT EXISTS user_tags (
  userId CHAR(36) NOT NULL,
  tagId CHAR(36) NOT NULL,
  PRIMARY KEY (userId, tagId),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (tagId) REFERENCES tags(id) ON DELETE CASCADE
)