"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ENDPOINT = void 0;
var ENDPOINT;
(function (ENDPOINT) {
    ENDPOINT["SIGNUP"] = "/api/v0/signup";
    ENDPOINT["LOGIN"] = "/api/v0/login";
    ENDPOINT["GET_USER_CARD"] = "/api/v0/user/:id";
    ENDPOINT["FOLLOW_USER"] = "/api/v0/user/:id/follow";
    ENDPOINT["UNFOLLOW_USER"] = "/api/v0/user/:id/unfollow";
    ENDPOINT["GET_FOLLOWERS"] = "/api/v0/user/:id/followers";
    ENDPOINT["GET_USERS_LIST"] = "/api/v0/users";
    ENDPOINT["GET_USER_BLOGS"] = "/api/v0/user/:id/blogs/:page";
    ENDPOINT["GET_USER_SPACES"] = "/api/v0/user/:id/spaces";
    ENDPOINT["GET_ALL_UNREAD_MSGS"] = "/api/v0/user/msgs/missed";
    ENDPOINT["CREATE_BLOG"] = "/api/v0/blog";
    ENDPOINT["UPDATE_BLOG"] = "/api/v0/blog/:blogId";
    ENDPOINT["GET_BLOG"] = "/api/v0/blog/:blogId";
    ENDPOINT["DELETE_BLOG"] = "/api/v0/blog/:blogId";
    ENDPOINT["GET_BLOG_COMMENTS"] = "/api/v0/blog/:blogId/comments";
    ENDPOINT["GET_BLOG_LIKES"] = "/api/v0/blog/:blogId/likes";
    ENDPOINT["GET_BLOG_LIKES_LIST"] = "/api/v0/blog/:blogId/likes/list";
    ENDPOINT["LIKE_BLOG"] = "/api/v0/blog/:blogId/like";
    ENDPOINT["UNLIKE_BLOG"] = "/api/v0/blog/:blogId/unlike";
    ENDPOINT["NUM_OF_COMMENTS"] = "/api/v0/blog/:blogId/num-of-comments";
    ENDPOINT["CREATE_SHORT"] = "/api/v0/space/:spaceId/short";
    ENDPOINT["UPDATE_SHORT"] = "/api/v0/short/:shortId";
    ENDPOINT["GET_SHORT"] = "/api/v0/short/:shortId";
    ENDPOINT["DELETE_SHORT"] = "/api/v0/short/:shortId";
    ENDPOINT["GET_SHORT_COMMENTS"] = "/api/v0/short/:shortId/comments";
    ENDPOINT["GET_SHORT_LIKES"] = "/api/v0/short/:shortId/likes";
    ENDPOINT["GET_SHORT_LIKES_LIST"] = "/api/v0/short/:shortId/likes/list";
    ENDPOINT["LIKE_SHORT"] = "/api/v0/short/:shortId/like";
    ENDPOINT["UNLIKE_SHORT"] = "/api/v0/short/:shortId/unlike";
    ENDPOINT["CREATE_COMMENT"] = "/api/v0/blog/:blogId/comment";
    ENDPOINT["UPDATE_COMMENT"] = "/api/v0/comment/:commentId";
    ENDPOINT["DELETE_COMMENT"] = "/api/v0/comment/:commentId";
    ENDPOINT["CREATE_SPACE"] = "/api/v0/space";
    ENDPOINT["UPDATE_SPACE"] = "/api/v0/space/:spaceId";
    ENDPOINT["GET_SPACE"] = "/api/v0/space/:spaceId";
    ENDPOINT["DELETE_SPACE"] = "/api/v0/space/:spaceId";
    ENDPOINT["GET_SPACE_BLOGS"] = "/api/v0/space/:spaceId/blogs/:page";
    ENDPOINT["GET_DEFAULT_SPACE"] = "/api/v0/space";
    ENDPOINT["JOIN_SPACE"] = "/api/v0/space/:spaceId/join";
    ENDPOINT["ADD_MEMBER"] = "/api/v0/space/:spaceId/member";
    ENDPOINT["GET_SPACE_MEMBERS"] = "/api/v0/space/:spaceId/members";
    ENDPOINT["Get_SPACE_CHAT"] = "/api/v0/space/:spaceId/chat";
    ENDPOINT["DELETE_MEMBER"] = "/api/v0/space/:spaceId/member/:memberId";
    ENDPOINT["LEAVE_SPACE"] = "/api/v0/space/:spaceId/leave";
    ENDPOINT["GET_UNREAD_MSGS_NUM"] = "/api/v0/space/:spaceId/unread-msgs";
    ENDPOINT["CREATE_MESSAGE"] = "/api/v0/space/:spaceId/message";
    ENDPOINT["DELETE_MESSAGE"] = "/api/v0/message/:msgId";
    ENDPOINT["LIKE_POST"] = "/api/v0/post/:postId/like";
    ENDPOINT["UNLIKE_POST"] = "/api/v0/post/:postId/unlike";
    ENDPOINT["GET_POST_LIKES"] = "/api/v0/post/:postId/likes";
    ENDPOINT["GET_FEEDS"] = "/api/v0/feeds";
    ENDPOINT["GET_FEEDS_PAGE"] = "/api/v0/feeds/:page";
})(ENDPOINT || (exports.ENDPOINT = ENDPOINT = {}));
